### ISSUE TITLE
Bug: "A newer .NET Framework is required" even though the latest version is installed

### ISSUE THREAD

**Issue by ColinTimBarndt** [walterpg/google-drive-sync#52] opened 2021-09-23 08:05 UTC
**Describe the bug**
It is impossible for me to load the plugin in KeePass on Linux because of this error message:
![Screenshot from 2021-09-23 09-57-26](https://user-images.githubusercontent.com/26167910/134472673-c4fc9631-43de-443f-a436-4ac629d76808.png)

**To Reproduce**
1. Install the preview version of .NET (version 6)
2. Verify the installation using `dotnet --version`
3. Install the plugin
4. Restart KeePass
5. See error

**Expected behavior**
The plugin should find the installed version of .NET and compile.

**Screenshots**
![image](https://user-images.githubusercontent.com/26167910/134472967-9d8b0705-567d-48d9-95ab-a773ddc8fd67.png)

**Please provide the following information:**
 - Pop!_OS 21.04 64-bit, GNOME Version 3.38.5, Windowing System X11
 - Mozilla Firefox 92.0 (64-bit) for Ubuntu cononcial - 1.0
 - Plugin Version 4.0.7
 - KeePass Version 2.47 (64-bit) "Normal"
 - Other plugins: KeeTrayTOTP

**Comment by dregad** [comment] 2021-10-01 07:37
Duplicate of #26

**Closed** 2021-10-01 08:17 UTC
