### ISSUE TITLE
Version 4.0.7 will not detected as actually Version in KP 2.48.1

### ISSUE THREAD

**Issue by amarradi** [walterpg/google-drive-sync#46] opened 2021-06-16 09:30 UTC
**Describe the bug**
I updated the file with the new Version 4.0.7beta. One time a day i get the notification that a new Version 4.0.7 is available. After i downloaded the new beta two times i write this ticket. The Version will not detected as the new Version.

KP recognises the plugin as if I had installed version 4.0.6

I downloaded from thist page 
https://github.com/walterpg/google-drive-sync/releases

**Expected behavior**

**Screenshots**

**Please provide the following information:**
 - OS: Windows 10 Pro Build 19043.1055
 - Browser and version: FF 89.0
 - Plugin Version: 4.0.7
 - KeePass Version: 2.48.1
 - "Portable" or "Normal" KP installation?: normal
 - List all other plugins in use, and their version: no plugins

**Additional context**

**Comment by erose524** [comment] 2021-06-22 18:45
I had a similar issue and what fixed it for me was clearing my plugins cache. In Tools>Plugins there's a section called Plugin Cache and the option to clear it. After clearing this cache and restarting KeePass, the plugin was viewed as up to date for me. Hope this helps you as well!

**Comment by amarradi** [comment] 2021-06-23 11:19
Hello erose524,

Yes, tust solved my Problem. Thanks.

**Comment by walterpg** [comment] 2021-08-22 20:21
Duplicate of #43, will be fixed in the next release.

**Comment by walterpg** [comment] 2022-01-30 16:09
Fixed by resolution of #43 (via walterpg/plgx-build-tasks#1).

**Closed by walterpg** 2022-01-30 16:09 UTC
Labels: duplicate
